name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 14 (Angular 11)
        uses: actions/setup-node@v4
        with:
          node-version: '14.15.5'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        run: npm run build

      - name: Upload dist artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/angular-frontend

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify deploy hook
        env:
          NETLIFY_DEPLOY_HOOK: ${{ secrets.NETLIFY_DEPLOY_HOOK }}
        run: |
          if [ -z "$NETLIFY_DEPLOY_HOOK" ]; then
            echo "NETLIFY_DEPLOY_HOOK secret not set; skipping Netlify deploy trigger."
            exit 0
          fi
          curl -s -X POST "$NETLIFY_DEPLOY_HOOK"
